runtime: php82
env: flexible
handlers:
- url: /.*
  script: public/index.php
runtime_config:
  document_root: public
skip_files:
- .gitignore
- .gitattributes
- composer.lock
- phpunit.xml
- phpcs.xml
- phpdcd.xml
- phpmd.xml
- .env
- .env.example
- storage/*
- node_modules/*
