runtime: php82
env: standard
handlers:
- url: /.*
  script: public/index.php
runtime_config:
  document_root: public
  php_version: 8.0

beta_settings:
  cloud_sql_instances: glassy-landing-384714:us-central1:boutique

