runtime: php
env: flex
runtime_config:
  document_root: public
  php_version: 8.2

skip_files:
  .env

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:bk2GBnOUDrcjVgblsgep6SZcja2pUpnC8K40XP4UMno=
  STORAGE_DIR: /tmp
